# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - DB=MYSQL

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL
    - php: 5.6
      env: DB=PGSQL
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit jsontext/tests
